import turtle

screen = turtle.Screen()
screen.screensize(500,500)
screen.bgcolor("lightblue1")

t = turtle.Turtle()
t.speed(0)

#water
t.penup()
t.goto(-5000,50)
t.pendown()
t.fillcolor("dodgerblue4")
t.pencolor("dodgerblue4")
t.begin_fill()
t.goto(5000,50)
t.goto(5000,-150)
t.goto(-5000,-150)
t.goto(-5000,50)
t.end_fill()

#sand
t.penup()
t.goto(-5000,-50)
t.pendown()
t.fillcolor("bisque1")
t.pencolor("bisque1")
t.begin_fill()
t.goto(5000,-100)
t.goto(5000,-5000)
t.goto(-5000,-5000)
t.goto(-5000,-50)
t.end_fill()

#sun
t.penup()
t.goto(-225,225)
t.pendown()
t.fillcolor("gold1")
t.pencolor("gold1")
t.begin_fill()
t.circle(60)
t.end_fill()

#cloud
t.penup()
t.goto(50,230)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.goto(50,300)
t.goto(250,300)
t.goto(250,230)
t.goto(50,230)
t.end_fill()
#1st circle of the clouds
t.penup()
t.goto(50,230)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()
#2nd circle of the clouds
t.penup()
t.goto(75,260)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()
#3rd circle of the clouds
t.penup()
t.goto(115,275)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()
#4th circle of the clouds
t.penup()
t.goto(150,280)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()
#5th circle of the clouds
t.penup()
t.goto(195,275)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()
#6th circle of the clouds
t.penup()
t.goto(230,260)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()
#7th circle of the clouds
t.penup()
t.goto(260,230)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()



#umbrella stick
t.penup()
t.goto(-220,-175)
t.pendown()
t.fillcolor("silver")
t.pencolor("silver")
t.begin_fill()
t.goto(-220,-350)
t.goto(-210,-350)
t.goto(-210,-175)
t.goto(-220,-175)
t.end_fill()

#umbrella top
t.penup()
t.goto(-117,-225)
t.pendown()
t.pencolor("pink")
t.fillcolor("pink")
t.setheading(90)
t.begin_fill()
t.circle(95,180)
t.end_fill()


#umbrella curve #1
t.penup()
t.goto(-120,-225)
t.pendown()
t.pencolor("bisque1")
t.fillcolor("bisque1")
t.setheading(90)
t.begin_fill()
t.circle(30,180)
t.end_fill()

#umbrella curve #2
t.pencolor("bisque1")
t.fillcolor("bisque1")
t.setheading(90)
t.begin_fill()
t.circle(30,180)
t.end_fill()

#umbrella curve #3
t.pencolor("bisque1")
t.fillcolor("bisque1")
t.setheading(90)
t.begin_fill()
t.circle(30,180)
t.end_fill()

#sand bucket
t.penup()
t.goto(-100,-300)
t.pendown()
t.fillcolor("red")
t.pencolor("red")
t.begin_fill()
t.goto(-100,-350)
t.goto(-140,-350)
t.goto(-140,-300)
t.goto(-100,-300)
t.end_fill()

#bucket top
t.penup()
t.goto(-140,-300)
t.pendown()
t.pencolor("darkred")
t.fillcolor("darkred")
t.begin_fill()
t.circle(20,180)
t.end_fill()

#towel
t.penup()
t.goto(0,-175)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.goto(0,-325)
t.goto(100,-325)
t.goto(100,-175)
t.goto(0,-175)
t.end_fill()

#towel stripe 1
t.penup()
t.goto(15,-175)
t.pendown()
t.fillcolor("MediumPurple1")
t.pencolor("MediumPurple1")
t.begin_fill()
t.goto(15,-325)
t.goto(25,-325)
t.goto(25,-175)
t.goto(15,-175)
t.end_fill()

#towel stripe 2
t.penup()
t.goto(45,-175)
t.pendown()
t.fillcolor("MediumPurple1")
t.pencolor("MediumPurple1")
t.begin_fill()
t.goto(45,-325)
t.goto(55,-325)
t.goto(55,-175)
t.goto(45,-175)
t.end_fill()

#towel stripe 3
t.penup()
t.goto(75,-175)
t.pendown()
t.fillcolor("MediumPurple1")
t.pencolor("MediumPurple1")
t.begin_fill()
t.goto(75,-325)
t.goto(85,-325)
t.goto(85,-175)
t.goto(75,-175)
t.end_fill()

#beach ball
t.penup()
t.goto(225,-310)
t.pendown()
t.fillcolor("light blue")
t.pencolor("light blue")
t.begin_fill()
t.circle(45)
t.end_fill()

#magenta polka dots
t.penup()
t.goto(220,-312)
t.pendown()
t.fillcolor("magenta")
t.pencolor("magenta")
t.begin_fill()
t.circle(5)
t.end_fill()

#magenta polka dots
t.penup()
t.goto(180,-286)
t.pendown()
t.fillcolor("magenta")
t.pencolor("magenta")
t.begin_fill()
t.circle(5)
t.end_fill()

#purple polka dots
t.penup()
t.goto(190,-325)
t.pendown()
t.fillcolor("Purple2")
t.pencolor("Purple2")
t.begin_fill()
t.circle(5)
t.end_fill()

#purple polka dots
t.penup()
t.goto(155,-310)
t.pendown()
t.fillcolor("Purple2")
t.pencolor("Purple2")
t.begin_fill()
t.circle(5)
t.end_fill()

#Blue polka dots
t.penup()
t.goto(175,-343)
t.pendown()
t.fillcolor("DeepSkyBlue2")
t.pencolor("DeepSkyBlue2")
t.begin_fill()
t.circle(5)
t.end_fill()

#Blue polka dots
t.penup()
t.goto(208,-293)
t.pendown()
t.fillcolor("DeepSkyBlue2")
t.pencolor("DeepSkyBlue2")
t.begin_fill()
t.circle(5)
t.end_fill()

#Green polka dots
t.penup()
t.goto(175,-309)
t.pendown()
t.fillcolor("green3")
t.pencolor("green3")
t.begin_fill()
t.circle(5)
t.end_fill()

#Green polka dots
t.penup()
t.goto(195,-344)
t.pendown()
t.fillcolor("green3")
t.pencolor("green3")
t.begin_fill()
t.circle(5)
t.end_fill()

#Yellow polka dots
t.penup()
t.goto(155,-330)
t.pendown()
t.fillcolor("gold1")
t.pencolor("gold1")
t.begin_fill()
t.circle(5)
t.end_fill()

#Yellow polka dots
t.penup()
t.goto(210,-325)
t.pendown()
t.fillcolor("gold1")
t.pencolor("gold1")
t.begin_fill()
t.circle(5)
t.end_fill()

#coconut
t.penup()
t.goto(255,-300)
t.pendown()
t.setheading(280)
t.pencolor("sienna4")
t.fillcolor("sienna4")
t.begin_fill()
t.circle(25,180)
t.end_fill()

#coconut top
t.penup()
t.goto(265,-298)
t.pendown()
t.setheading(280)
t.pencolor("seashell")
t.fillcolor("seashell")
t.begin_fill()
t.circle(13,180)
t.end_fill()

#tube
t.penup()
t.goto(-150,-20)
t.pendown()
t.setheading(280)
t.pencolor("DeepPink1")
t.fillcolor("DeepPink1")
t.begin_fill()
t.circle(50)
t.end_fill()

#tube hole
t.penup()
t.goto(-126,-17)
t.pendown()
t.setheading(280)
t.pencolor("dodgerblue4")
t.fillcolor("dodgerblue4")
t.begin_fill()
t.circle(25,)
t.end_fill()

#right tube dash
t.penup()
t.goto(-150,-10)
t.pendown()
t.pencolor("white")
t.fillcolor("white")
t.pensize(5)
t.goto(-130,-10)

#left tube dash
t.penup()
t.goto(-74,-10)
t.pendown()
t.pencolor("white")
t.fillcolor("white")
t.pensize(5)
t.goto(-54,-10)

#top tube dash
t.penup()
t.goto(-102,35)
t.pendown()
t.pencolor("white")
t.fillcolor("white")
t.pensize(5)
t.goto(-102,15)

#bottom tube dash
t.penup()
t.goto(-102,-60)
t.pendown()
t.pencolor("white")
t.fillcolor("white")
t.pensize(5)
t.goto(-102,-40)

t.penup()
t.goto(0,150)
t.pendown()
t.pencolor("Pink")
t.write("Happy Spring",font=("Arial",40,"bold italic"),align="center")
turtle.done()